apiVersion: v1
kind: Human
metadata:
  name: Dennis Sterzenbach
  namespace: Berlin
  pronouns: he/him
spec:
  job: Senior Specialist & Software Architect
  mode: DevOps
  company: DB Systel GmbH
  social: https://mastodon.social/@nister
